# Generated by Django 2.2 on 2019-05-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_paid', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('pilgrim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrim_id', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
